### ISSUE TITLE
[Light Bulb] Max value of color Temp. is different from SmartThings

### ISSUE THREAD

**Issue by spdkimo** [Samsung/ioter#104]
Max value of color Temperature is 65279K on ioter which is same as Matter specification, but SmartThings shows it to 30000K. It needs to be match each other

**Comment by jinwon0325kim** [comment]
Currently, light bulb is set to **Color Temperature Light(0x010c)**. 
so, the light bulb can set light on/off, dimmer, and color temperature.
However, the range of color temperature cannot be set.
The default value of the range of the ST app is 1-30000 kelvins, but 1 kelvin is a value that cannot be obtained as shown below.
`[3.42] Color temperature in kelvins = 1,000,000 / ColorTemperatureMireds, where ColorTemperatureMireds is in the range 1 to 65279 mireds inclusive, giving a color temperature range from 1,000,000 kelvins to 15.32 kelvins.`

LightStrip of Nanoleaf is set to **Extended Color Light(0x010d).**
so, the lightstrip can set light on/off, dimmer, color, and color temperature.
In addition, the color temperature value of the ST app can be used as 2580~7050 kelvins.
in light bulb, **Color Temperature Light** cannot be used because the range contains values that cannot be used like 1 kelvin.
So we should use **Extended Color Light** or **Dimmable Light(0x0101)**.
**Dimmable Light** can delete color temperature from ui now.
**Extended Color Light** should be added so that color can be set.
We can choose **Dimmable Light** to change it simply.

**Comment by spdkimo** [comment]
Action
1. **Dimmable Light**
2. Extended Color Light
3. Setting MIN/MAX value
